lightning_module:
  _target_: sidon.model.dialogue_sidion.lightning_module.DialogueFeaturePredictorWithTransformerDiscriminatorLightningModule
  _recursive_: false

cfg:
  ssl_model_name: facebook/w2v-bert-2.0

  discriminator:
    hidden_size: 1024
    num_layers: 2
    num_heads: 8
    ff_mult: 4.0
    dropout: 0.5
    adv_weight: 0.001

  optim:
    lr: 1e-4
    weight_decay: 1e-3
