lightning_module:
  _target_: sidon.model.dialogue_sidion.lightning_module.DialogueSidonDiffusionLightningModule
  _recursive_: false

cfg:
  lora: true
  sample_rate: 24000
  ssl_model_name: facebook/w2v-bert-2.0
  vae_checkpoint_path: /home/qch10240fz/nakata/github.com/Sidon/sidon/jhqmq4u3/checkpoints/epoch=0-step=510000.ckpt

  activation_checkpointing: true

  diffusion_head:
    hidden_size: 768
    head_layers: 8
    num_heads: 12
    head_ffn_ratio: 4.0
    use_positional: true

  diffusion:
    num_train_timesteps: 1000
    num_inference_steps: 30
    prediction_type: v_prediction

  latent_normalization:
    enabled: true
    eps: 1.0e-6

  optim:
    lr: 1e-4
    weight_decay: 0.01
