lightning_module:
  _target_: sidon.model.dialogue_sidion.lightning_module.DialogueSidonNoVaeLatentWithDiffusionHeadLightningModule
  _recursive_: false

cfg:
  lora: true
  ssl_model_name: facebook/w2v-bert-2.0
  teacher_feature_layer: 8

  diffusion_head:
    hidden_size: 768
    head_layers: 8
    num_heads: 12
    head_ffn_ratio: 4.0
    use_positional: true

  diffusion:
    num_train_timesteps: 1000
    num_inference_steps: 1000
    prediction_type: v_prediction

  feature_normalization:
    enabled: true
    eps: 1.0e-6

  optim:
    lr: 1e-5
    weight_decay: 0.01
