lightning_module:
  _target_: sidon.model.geneses.lightning_module.GenesesLightningModule
  _recursive_: false

cfg:
  sample_rate: 24000

  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-5
    weight_decay: 1e-4

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 100
    eta_min: 1e-6

  vae:
    hf_hub:
      repo_id: koacai/geneses
      filename: dacvae_l16_librittsr.pt
    hidden_size: 16
    max_duration: 20
    sample_rate: 24000
    noise_amp: 1e-4

  mmdit:
    in_channels: ${model.cfg.vae.hidden_size}
    in_ssl_channels: 1024
    out_channels: ${model.cfg.vae.hidden_size}
    hidden_size: 768
    max_ssl_seq_len: 2000
    max_seq_len: 5000
    depth: 12
    heads: 12

  ssl_model:
    name: facebook/w2v-bert-2.0
    layer: -1
    sample_rate: 16000

  t_sampling_schema: logit_normal  # [uniform, logit_normal]
