lightning_module:
  _target_: sidon.model.dialogue_sidion.lightning_module.SepformerLightningModule
  _recursive_: false

cfg:
  model_sample_rate: 24000
  output_sample_rate: 24000
  train_crop_seconds: 10.0
  val_log_batches: 5

  sepformer:
    num_speakers: 2
    encoder_kernel_size: 23
    masknet_chunksize: 375
    encoder_out_nchannels: 256
    intra_numlayers: 8
    inter_numlayers: 8
    intra_nhead: 8
    inter_nhead: 8
    intra_dffn: 1024
    inter_dffn: 1024
    intra_use_positional: true
    inter_use_positional: true
    intra_norm_before: true
    inter_norm_before: true

  optim:
    lr: 1e-4
    weight_decay: 0.01
    warmup_steps: 2000
