logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  name: null
  project: sidon

callbacks:
  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: step

trainer:
  fast_dev_run: false
  max_steps: 2_000_000
  val_check_interval: 5_000
  strategy:
    _target_: lightning.pytorch.strategies.DDPStrategy
    static_graph: true
  limit_val_batches: 1000
  precision: 32
  gradient_clip_val: 0.5
  gradient_clip_algorithm: "norm"
  plugins:
    _target_: sidon.util.ABCIEnvironment
ckpt_path: null
compile: false
